default_job = "check"

[jobs.check]
command = ["cargo", "check"]

[jobs.run]
command = ["cargo", "run"]
need_stdout = true

[jobs.test]
command = ["cargo", "test"]

[jobs.ci]
command = [
    "sh", "-c",
    "cargo fmt && cargo clippy && cargo audit && cargo test && cargo tarpaulin --ignore-tests"
]
need_stdout = true

[keybindings]
k = "job:check"
c = "job:ci"
r = "job:run"
t = "job:test"
